# Generated by Django 5.1.6 on 2025-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='sites_photos/')),
            ],
        ),
    ]
