# Generated by Django 5.1.6 on 2025-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteentrepot',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='sites_docs/'),
        ),
    ]
