# Generated by Django 5.1.6 on 2025-06-23 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cleaning', 'Nettoyage'), ('inspection', 'Inspection'), ('part_replacement', 'Remplacement de pièce'), ('calibration', 'Étalonnage')], max_length=50)),
                ('description', models.TextField()),
                ('frequency_days', models.PositiveIntegerField(default=30)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('assigned_to', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('color_code', models.CharField(default='#6c757d', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Effectuée'), ('postponed', 'Reportée'), ('incomplete', 'Inachevée'), ('missed', 'Manquée')], default='pending', max_length=20)),
                ('postponed_to', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading_date', models.DateField(default=django.utils.timezone.now)),
                ('reading_time', models.TimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(max_length=100)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_readings', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Relevé de température',
                'ordering': ['-reading_date', '-reading_time'],
            },
        ),
    ]
