# Generated by Django 5.1.6 on 2025-07-17 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Code unique généré automatiquement', max_length=8, unique=True)),
                ('specialty', models.CharField(choices=[('SOU', 'Soudure'), ('FUI', 'Fuites'), ('ELE', 'Électricité'), ('AUT', 'Autre')], max_length=3, verbose_name='Spécialité')),
                ('status', models.CharField(choices=[('INTRV', 'En intervention'), ('BOOK', 'Réservée'), ('AVAIL', 'Disponible')], default='AVAIL', max_length=5, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(help_text='Membres de l’équipe', related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
