# Generated by Django 5.1.6 on 2025-06-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('family', models.CharField(choices=[('CF', 'Chambre Froide'), ('CG', 'Congélateur')], max_length=2, verbose_name='Famille')),
                ('sub_family', models.CharField(max_length=100, verbose_name='Sous-famille')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Capacité (T)')),
                ('site', models.CharField(choices=[('digue', 'DIGUE'), ('cittma', 'CITTMA'), ('sotranav', 'SOTRANAV'), ('E1', 'ESSENGUE 1'), ('E2', 'ESSENGUE 2'), ('E3', 'ESSENGUE 3'), ('E4', 'ESSENGUE 4'), ('E5', 'ESSENGUE 5'), ('E6', 'ESSENGUE 6'), ('bonaberi', 'BONABERI')], max_length=100, verbose_name='Site')),
                ('number', models.CharField(max_length=50, verbose_name='Numéro')),
                ('group_count', models.IntegerField(verbose_name='Nombre de groupes')),
                ('power_per_group', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puissance/groupe (kW)')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Constructeur')),
                ('temperature_setpoint', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T° consigne')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('panne', 'En panne'), ('arret', 'Arrêt')], max_length=10, verbose_name='Statut')),
                ('commissioning_date', models.DateField(verbose_name='Date de mise en service')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='equipments/docs/', verbose_name='Documentation')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['family', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COND', 'Groupe de condensation'), ('EVAP', "Groupe d'évaporation"), ('COMP', 'Compresseur'), ('DET', 'Détendeur')], max_length=4)),
                ('code', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('caracteristiques', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/images/', verbose_name='Image')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_ensembles', to='equipments.equipment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='equipments.sousensemble')),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
    ]
