# Generated by Django 5.1.6 on 2025-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousensemble',
            name='type',
            field=models.CharField(choices=[('COND', 'Groupe de condensation'), ('EVAP', "Groupe d'évaporation"), ('COMP', 'Compresseur'), ('DET', 'Détendeur'), ('PRESSHP', 'Pressostat HP'), ('PRESSBP', 'Pressostat BP'), ('PRESSHL', 'Pressostat Huile'), ('VAN', 'Electrovanne'), ('BACL', 'Bouteille anti CL'), ('RESERVOIR', 'Réservoir de liquide'), ('FILTREDES', 'Filtre déshydrateur'), ('VOY', 'Voyant'), ('OILSEP', "Séparateur d'huile"), ('VENTILO', 'Ventilateur'), ('CAPACITOR', 'Condensateur'), ('RESISTANCE', 'Résistance chauffante'), ('PANNEAU', "Panneau d'isolation"), ('LUMI', 'Luminaire'), ('RIDAIR', "Rideau d'air"), ('RIDLAN', 'Rideau à lanière')], max_length=12),
        ),
    ]
