# Generated by Django 5.1.6 on 2025-07-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepots', '0002_siteentrepot_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois concerné')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la facture (FCFA)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='entrepots.siteentrepot')),
            ],
            options={
                'ordering': ['-mois'],
                'unique_together': {('site', 'mois')},
            },
        ),
    ]
