# Generated by Django 5.1.6 on 2025-06-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='fa-box', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('caracteristiques', models.TextField()),
                ('quantite', models.IntegerField()),
                ('objet', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('initie_par', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='attente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.categorie')),
            ],
            options={
                'db_table': 'stockapp_commande',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('famille', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('fournisseur', models.CharField(max_length=100)),
                ('caracteristiques', models.TextField(blank=True, null=True, verbose_name='Caractéristiques techniques')),
                ('quantite', models.IntegerField(verbose_name='Qté en stock')),
                ('stock_alerte', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.categorie')),
            ],
            options={
                'ordering': ['-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.produit')),
            ],
        ),
    ]
