# Generated by Django 5.1.6 on 2025-06-23 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('pannes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('urgence', models.CharField(choices=[('H', 'Haute'), ('M', 'Moyenne'), ('B', 'Basse')], default='M', max_length=1)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('N', 'Nouvelle'), ('E', 'En cours'), ('T', 'Terminée'), ('A', 'Annulée'), ('R', 'Reportée')], default='N', max_length=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='equipments.equipment')),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='pannes.panne')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OrdreTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_planifiee', models.DateTimeField()),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('equipe', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('P', 'Planifié'), ('E', 'En cours'), ('T', 'Terminé'), ('A', 'Annulé')], default='P', max_length=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres', to='intervention.demandeintervention')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres', to='equipments.equipment')),
                ('sous_ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.sousensemble')),
            ],
            options={
                'verbose_name': 'Ordre de travail',
                'verbose_name_plural': 'Ordres de travail',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('actions', models.TextField()),
                ('pieces_utilisees', models.TextField(blank=True)),
                ('temps_passe', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('S', 'Succès'), ('E', 'Échec'), ('R', 'Reporté'), ('N', 'Nécessite autre intervention')], max_length=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='intervention.ordretravail')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
                'ordering': ['-date_creation'],
            },
        ),
    ]
