# Generated by Django 5.1.6 on 2025-06-23 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé de la panne')),
                ('niveau_alerte', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='moyen', max_length=10, verbose_name="Niveau d'alerte")),
                ('code_panne', models.CharField(editable=False, max_length=20, unique=True)),
                ('emetteur', models.CharField(max_length=100, verbose_name="Nom de l'émetteur")),
                ('site', models.CharField(max_length=100)),
                ('date_heure_panne', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de la panne')),
                ('description', models.TextField(verbose_name='Description de la panne')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('resolue', models.BooleanField(default=False)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment', verbose_name='Équipement concerné')),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-date_heure_panne'],
            },
        ),
    ]
